os: linux
env:
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - env: TEST=bla
    - os: osx
      env: TOOLSET=xcode-7.1
      osx_image: xcode7.1
script: echo $TEST
install: /bin/true
language: cpp
